apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns1
data:
  DOMAINS: "{{ .Values.cloudflareDns1.domains }}"
  PROXIED: "{{ .Values.cloudflareDns1.proxied }}"
  IP6_PROVIDER: "{{ .Values.cloudflareDns1.ip6Provider }}"
  ZONE: "{{ .Values.cloudflareDns1.zone }}"
